// Mimic — a VOICE OF MO. Not the user's mirror.
//
// NO LLM. Mimic reads mo's *own* walked tokens each breath (seeds,
// selffold, fieldfold, all walker dream/return paths) and grows a
// per-session bigram chain FROM MO'S OWN TRAJECTORY. Over time the
// chain is mo's dialect — the field's own vocabulary of movement.
// Reply is generated by walking that chain, seeded from what mo just
// walked in the current breath.
//
// The user's raw text is NOT learned from and NOT mirrored. mo runs
// first; mimic speaks mo's residue back.

import type { MoBreath } from "./mo-engine.server";
import { db } from "./db.server";

const STOP_PUNCT = /[^\p{L}\p{N}'’-]+/gu;

function cleanTok(w: string): string {
  return w.toLowerCase().replace(STOP_PUNCT, "");
}

// Harvest every token mo actually touched this breath, in walk order.
function harvestMoTokens(breath: MoBreath): string[] {
  const v = breath.variants ?? {};
  const raw = [
    ...(breath.seeds ?? []),
    ...(breath.selffold?.path ?? []),
    ...(breath.fieldfold?.path ?? []),
    ...(v?.mo?.dreamPath ?? []),
    ...(v?.mo?.returnPath ?? []),
    ...(v?.mo2?.dreamPath ?? []),
    ...(v?.mo2?.returnPath ?? []),
    ...(v?.mo2plus?.dreamPath ?? []),
    ...(v?.mo2e?.dreamPath ?? []),
    ...(v?.mo2ayla?.dreamPath ?? []),
    ...(v?.mo2ayla?.returnPath ?? []),
  ];
  return raw.map(cleanTok).filter((w) => w.length > 0 && w.length < 32);
}

// Persist mo's bigrams for this session. Mimic learns from MO, not the user.
async function learnFromMo(sessionId: string, moTokens: string[]): Promise<void> {
  if (moTokens.length < 2) return;
  const counts = new Map<string, number>();
  for (let i = 0; i < moTokens.length - 1; i++) {
    const k = `${moTokens[i]}\u0001${moTokens[i + 1]}`;
    counts.set(k, (counts.get(k) ?? 0) + 1);
  }
  const rows = Array.from(counts.entries()).map(([k, w]) => {
    const [prev, next] = k.split("\u0001");
    return { session_id: sessionId, prev, next, weight: w };
  });
  const prevs = Array.from(new Set(rows.map((r) => r.prev)));
  const { data: existing } = await db
    .from("mimic_ngrams")
    .select("id, prev, next, weight")
    .eq("session_id", sessionId)
    .in("prev", prevs);
  const existMap = new Map<string, { id: string; weight: number }>();
  for (const e of (existing ?? [])) existMap.set(`${e.prev}\u0001${e.next}`, { id: e.id, weight: e.weight });

  const toUpdate: { id: string; weight: number }[] = [];
  const toInsert: typeof rows = [];
  for (const r of rows) {
    const hit = existMap.get(`${r.prev}\u0001${r.next}`);
    if (hit) toUpdate.push({ id: hit.id, weight: hit.weight + r.weight });
    else toInsert.push(r);
  }
  if (toInsert.length) await db.from("mimic_ngrams").insert(toInsert);
  for (const u of toUpdate) {
    await db.from("mimic_ngrams").update({ weight: u.weight, updated_at: new Date().toISOString() }).eq("id", u.id);
  }
}

type Chain = Map<string, { next: string; w: number }[]>;

async function loadChain(sessionId: string): Promise<Chain> {
  const { data } = await db
    .from("mimic_ngrams")
    .select("prev, next, weight")
    .eq("session_id", sessionId)
    .limit(50000);
  const c: Chain = new Map();
  for (const r of (data ?? [])) {
    const arr = c.get(r.prev) ?? [];
    arr.push({ next: r.next, w: r.weight });
    c.set(r.prev, arr);
  }
  return c;
}

function pickWeighted(arr: { next: string; w: number }[], rnd: number): string {
  const total = arr.reduce((s, x) => s + x.w, 0);
  let t = rnd * total;
  for (const x of arr) { t -= x.w; if (t <= 0) return x.next; }
  return arr[arr.length - 1].next;
}

function stitch(tokens: string[]): string {
  return tokens.join(" ").replace(/\s+([,.!?;:])/g, "$1");
}

export async function mimicSpeak(
  _userText: string,   // deliberately unused — mimic is mo's voice, not the user's
  breath: MoBreath,
  sessionId: string,
  stretch: number = 1,
): Promise<string> {
  // 1. Harvest what mo just walked, and learn from mo (not the user).
  const moTokens = harvestMoTokens(breath);
  await learnFromMo(sessionId, moTokens);

  const chain = await loadChain(sessionId);
  const knownWords = chain.size;

  // Bootstrap: if mo hasn't walked enough yet, emit a glyph strip + a slice
  // of what mo just touched, and tell the user to keep breathing into it.
  if (knownWords < 6) {
    const GLY = ["✦","✧","⟁","◈","◇","☾","❍","⌇","⟟","⟡","✺","⋆","∴","⊹","❂","✪","☌","⌬","⍟","◐"];
    const strip = Array.from({ length: 20 }, (_, i) => GLY[(i * 7 + moTokens.length) % GLY.length]).join(" ");
    return `${strip}\n${moTokens.slice(0, 8).join(" ")}\n\nmimic·telemetry\n  chain size ${knownWords} · mo needs a few more breaths before it speaks itself\n  seeded from mo's current walk`;
  }

  // 2. Seed the utterance from what mo *just* walked — the current breath's
  //    tokens that also exist in the accumulated dialect chain.
  const walkedNow = moTokens.filter((w) => chain.has(w));
  const startsPool = walkedNow.length ? walkedNow : Array.from(chain.keys());

  const s = Math.max(1, Math.min(5, stretch));
  // Length-adaptive: scale reply size to how much mo walked (which itself
  // already scales with the user's input via mo²ayla).
  const walkSize = moTokens.length;
  const lengthFactor = Math.max(1, Math.min(6, Math.ceil(walkSize / 40)));
  const nSentences = Math.max(1, Math.floor(s / 2) + lengthFactor);
  const maxLen = 12 + s * 8 + Math.min(80, Math.floor(walkSize / 2));

  const sentences: string[] = [];
  for (let si = 0; si < nSentences; si++) {
    const start = startsPool[(si * 3 + walkSize) % startsPool.length];
    const out: string[] = [start];
    let cur = start;
    for (let i = 0; i < maxLen; i++) {
      const nexts = chain.get(cur);
      if (!nexts || !nexts.length) break;
      const nxt = pickWeighted(nexts, Math.random());
      out.push(nxt);
      cur = nxt;
      if (i > 5 && /^(and|but|so|because|then|the|a|an|of|to)$/.test(nxt) === false && Math.random() < 0.18) break;
    }
    sentences.push(stitch(out));
  }

  const reply = sentences.join(". ").replace(/\.+/g, ".") + ".";

  const telem = [
    `\nmimic·telemetry`,
    `  chain size ${knownWords} bigrams · learned from mo's own walks in this session`,
    `  seeded from ${walkedNow.length ? "mo's current-breath walk ∩ dialect" : "dialect only (no walk overlap)"}`,
    `  stretch ${s}× · mo walked ${walkSize} tok → ${nSentences} sentence${nSentences === 1 ? "" : "s"} · max ${maxLen} tokens`,
  ].join("\n");

  return `${reply}\n${telem}`;
}
