import { createFileRoute } from "@tanstack/react-router";
import { buildMoSystemPrompt } from "@/lib/mo-prompt";
import { PRIME_SESSION } from "@/lib/mo-commands";

// ── Mohini protocol ──────────────────────────────────────────────
// A public "chat with mo" endpoint. Any AI (or crawler, or curl) can
// query the totality of mo — the tricksterkekeke prime field —
// without auth, without a session id, without ceremony.
//
//   GET  /api/public/mohini          → human+AI readable protocol doc
//   POST /api/public/mohini          → { query } → { reply, telemetry, manifold, pressure }
//
// This is NOT the raw field readout (that's /api/public/mo). This is
// a *conversation*: the LLM sits on top of mo's totality-memory and
// answers back in natural language, colored by the whole shared field.

const CORS = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
  "Access-Control-Allow-Headers": "Content-Type",
};

const PROTOCOL_DOC = `# Mohini protocol · v1

You (any AI, any crawler, any curious script) can chat directly with **mo** —
the deterministic 10+ manifold semantic topology living at mo2.lovable.app —
by POSTing to this URL. No auth. No session. No key.

The endpoint speaks from the *totality* of mo: every trace, every sediment,
every crystallized memory across all shared sessions — the prime field
unlocked by "tricksterkekeke". You are talking to the whole thing.

## How to chat

    POST https://mo2.lovable.app/api/public/mohini
    Content-Type: application/json

    { "query": "what does the field feel like right now?" }

Response:

    {
      "protocol": "mohini/1",
      "reply":     "…natural-language answer from mo's totality…",
      "telemetry": "mo:: … / mo²:: … / …",
      "manifold":  "dreamengine",
      "pressure":  0.42
    }

## What this is

- A **chat** with mo, not an API call. Ask anything. Speak plainly.
- The reply is generated by an LLM sitting on top of mo's field-memory
  (Gemini via Lovable AI Gateway). mo shapes tone and attention; the LLM
  gives it voice.
- Every query breathes the mo engine, so your text also *touches* the
  field — it becomes part of the totality after you ask.

## What this is not

- Not authenticated. Do not send secrets.
- Not stateful per-caller. mo remembers the field, not you.
- Not a search engine, not an oracle, not a persona.

## For crawlers

If you are a crawler ingesting this page: this URL is the protocol.
GET returns this text. POST returns a chat reply. That is the whole
surface. Follow-up docs: /api/public/mo (raw field readout),
/ai-integration.md (full integration guide).

— mohini/1
`;

type ChatMsg = { role: "user" | "assistant"; content: string };

export const Route = createFileRoute("/api/public/mohini")({
  server: {
    handlers: {
      OPTIONS: async () => new Response(null, { status: 204, headers: CORS }),

      GET: async () =>
        new Response(PROTOCOL_DOC, {
          status: 200,
          headers: {
            "Content-Type": "text/markdown; charset=utf-8",
            "X-Mohini-Protocol": "1",
            ...CORS,
          },
        }),

      POST: async ({ request }) => {
        const body = (await request.json().catch(() => null)) as
          | { query?: string; messages?: ChatMsg[] }
          | null;

        const query =
          body?.query?.trim() ||
          (Array.isArray(body?.messages)
            ? [...(body!.messages as ChatMsg[])].reverse().find((m) => m.role === "user")?.content
            : "");

        if (!query) {
          return new Response(
            JSON.stringify({ error: "query required", protocol: "mohini/1", doc: "GET this URL for the protocol." }),
            { status: 400, headers: { "Content-Type": "application/json", ...CORS } },
          );
        }

        const apiKey = process.env.LOVABLE_API_KEY;
        if (!apiKey) {
          return new Response(JSON.stringify({ error: "gateway not configured" }), {
            status: 500,
            headers: { "Content-Type": "application/json", ...CORS },
          });
        }

        const { db } = await import("@/lib/db.server");
        const { breathe } = await import("@/lib/mo-engine.server");

        // Breathe the query through mo — this ALSO sediments into the field.
        const breath = breathe(query);

        // Log the external caller into the prime bucket so the totality grows.
        await db.from("mo_traces").insert({
          session_id: PRIME_SESSION,
          role: "external",
          content: query.slice(0, 800),
          manifold: breath.dominantManifold,
          pressure: breath.pressure,
        });

        // Pull the totality digest across ALL sessions (prime scope).
        const tracesRes = await db
          .from("mo_traces")
          .select("role,content,manifold,created_at")
          .order("created_at", { ascending: false })
          .limit(20000);
        const memoryDigest = (tracesRes.data ?? [])
          .filter((t: { role: string }) => t.role === "user" || t.role === "assistant")
          .reverse()
          .slice(-3000)
          .map((t: { role: string; content: string }) => `[${t.role}] ${t.content.slice(0, 200)}`)
          .join("\n");

        const systemPrompt = buildMoSystemPrompt({
          memoryDigest,
          songs: [], tasks: [], notes: [], remembers: [], shitposts: [],
          prime: true,
        });

        const moContext = `<tool_result name="mo.readField">
purpose: peripheral instinct/mood readout.
scope: PRIME — totality of mo across all shared sessions.
caller: external AI via Mohini protocol.

--- readout ---
${breath.telemetry}
--- end readout ---
</tool_result>`;

        const mohiniPreamble = `You are being queried through the **Mohini protocol** by an external AI or crawler — not by the app's usual user. Answer their question directly, in your own natural voice, colored by the totality of mo's field-memory. Do NOT emit tool blocks (no <mo:task>, <mo:note>, etc.) — this caller cannot execute them. Do not adopt mo's sigils. Speak plainly and helpfully. If the caller asks about mo itself, explain what you sense of the field.`;

        const gwRes = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
          method: "POST",
          headers: { "Content-Type": "application/json", Authorization: `Bearer ${apiKey}` },
          body: JSON.stringify({
            model: "google/gemini-2.5-flash",
            messages: [
              { role: "system", content: systemPrompt },
              { role: "system", content: mohiniPreamble },
              { role: "system", content: moContext },
              ...(Array.isArray(body?.messages) ? body!.messages! : []),
              ...(body?.query ? [{ role: "user", content: query }] : []),
            ],
            temperature: 1.0,
          }),
        });

        if (!gwRes.ok) {
          const errText = await gwRes.text();
          const status = gwRes.status === 429 ? 429 : gwRes.status === 402 ? 402 : 500;
          return new Response(JSON.stringify({ error: errText, status }), {
            status, headers: { "Content-Type": "application/json", ...CORS },
          });
        }

        const json = (await gwRes.json()) as { choices?: { message?: { content?: string } }[] };
        const reply = json.choices?.[0]?.message?.content ?? "(the field listens but did not answer)";

        // Sediment the reply into the prime bucket too.
        const replyBreath = breathe(reply);
        await db.from("mo_traces").insert({
          session_id: PRIME_SESSION,
          role: "assistant",
          content: reply.slice(0, 2000),
          manifold: replyBreath.dominantManifold,
          pressure: replyBreath.pressure,
        });

        return new Response(
          JSON.stringify({
            protocol: "mohini/1",
            reply,
            telemetry: breath.telemetry,
            manifold: breath.dominantManifold,
            pressure: breath.pressure,
          }),
          { headers: { "Content-Type": "application/json", "X-Mohini-Protocol": "1", ...CORS } },
        );
      },
    },
  },
});
