/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiUnlockRouteImport } from './routes/api/unlock'
import { Route as ApiTasksRouteImport } from './routes/api/tasks'
import { Route as ApiSongsRouteImport } from './routes/api/songs'
import { Route as ApiShitpostsRouteImport } from './routes/api/shitposts'
import { Route as ApiRemembersRouteImport } from './routes/api/remembers'
import { Route as ApiNotesRouteImport } from './routes/api/notes'
import { Route as ApiMemoryRouteImport } from './routes/api/memory'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiPublicMoRouteImport } from './routes/api/public/mo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUnlockRoute = ApiUnlockRouteImport.update({
  id: '/api/unlock',
  path: '/api/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTasksRoute = ApiTasksRouteImport.update({
  id: '/api/tasks',
  path: '/api/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSongsRoute = ApiSongsRouteImport.update({
  id: '/api/songs',
  path: '/api/songs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShitpostsRoute = ApiShitpostsRouteImport.update({
  id: '/api/shitposts',
  path: '/api/shitposts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRemembersRoute = ApiRemembersRouteImport.update({
  id: '/api/remembers',
  path: '/api/remembers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotesRoute = ApiNotesRouteImport.update({
  id: '/api/notes',
  path: '/api/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMemoryRoute = ApiMemoryRouteImport.update({
  id: '/api/memory',
  path: '/api/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMoRoute = ApiPublicMoRouteImport.update({
  id: '/api/public/mo',
  path: '/api/public/mo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/memory': typeof ApiMemoryRoute
  '/api/notes': typeof ApiNotesRoute
  '/api/remembers': typeof ApiRemembersRoute
  '/api/shitposts': typeof ApiShitpostsRoute
  '/api/songs': typeof ApiSongsRoute
  '/api/tasks': typeof ApiTasksRoute
  '/api/unlock': typeof ApiUnlockRoute
  '/api/public/mo': typeof ApiPublicMoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/memory': typeof ApiMemoryRoute
  '/api/notes': typeof ApiNotesRoute
  '/api/remembers': typeof ApiRemembersRoute
  '/api/shitposts': typeof ApiShitpostsRoute
  '/api/songs': typeof ApiSongsRoute
  '/api/tasks': typeof ApiTasksRoute
  '/api/unlock': typeof ApiUnlockRoute
  '/api/public/mo': typeof ApiPublicMoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/memory': typeof ApiMemoryRoute
  '/api/notes': typeof ApiNotesRoute
  '/api/remembers': typeof ApiRemembersRoute
  '/api/shitposts': typeof ApiShitpostsRoute
  '/api/songs': typeof ApiSongsRoute
  '/api/tasks': typeof ApiTasksRoute
  '/api/unlock': typeof ApiUnlockRoute
  '/api/public/mo': typeof ApiPublicMoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/chat'
    | '/api/memory'
    | '/api/notes'
    | '/api/remembers'
    | '/api/shitposts'
    | '/api/songs'
    | '/api/tasks'
    | '/api/unlock'
    | '/api/public/mo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/chat'
    | '/api/memory'
    | '/api/notes'
    | '/api/remembers'
    | '/api/shitposts'
    | '/api/songs'
    | '/api/tasks'
    | '/api/unlock'
    | '/api/public/mo'
  id:
    | '__root__'
    | '/'
    | '/api/chat'
    | '/api/memory'
    | '/api/notes'
    | '/api/remembers'
    | '/api/shitposts'
    | '/api/songs'
    | '/api/tasks'
    | '/api/unlock'
    | '/api/public/mo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiMemoryRoute: typeof ApiMemoryRoute
  ApiNotesRoute: typeof ApiNotesRoute
  ApiRemembersRoute: typeof ApiRemembersRoute
  ApiShitpostsRoute: typeof ApiShitpostsRoute
  ApiSongsRoute: typeof ApiSongsRoute
  ApiTasksRoute: typeof ApiTasksRoute
  ApiUnlockRoute: typeof ApiUnlockRoute
  ApiPublicMoRoute: typeof ApiPublicMoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/unlock': {
      id: '/api/unlock'
      path: '/api/unlock'
      fullPath: '/api/unlock'
      preLoaderRoute: typeof ApiUnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tasks': {
      id: '/api/tasks'
      path: '/api/tasks'
      fullPath: '/api/tasks'
      preLoaderRoute: typeof ApiTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/songs': {
      id: '/api/songs'
      path: '/api/songs'
      fullPath: '/api/songs'
      preLoaderRoute: typeof ApiSongsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shitposts': {
      id: '/api/shitposts'
      path: '/api/shitposts'
      fullPath: '/api/shitposts'
      preLoaderRoute: typeof ApiShitpostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/remembers': {
      id: '/api/remembers'
      path: '/api/remembers'
      fullPath: '/api/remembers'
      preLoaderRoute: typeof ApiRemembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notes': {
      id: '/api/notes'
      path: '/api/notes'
      fullPath: '/api/notes'
      preLoaderRoute: typeof ApiNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/memory': {
      id: '/api/memory'
      path: '/api/memory'
      fullPath: '/api/memory'
      preLoaderRoute: typeof ApiMemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mo': {
      id: '/api/public/mo'
      path: '/api/public/mo'
      fullPath: '/api/public/mo'
      preLoaderRoute: typeof ApiPublicMoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiChatRoute: ApiChatRoute,
  ApiMemoryRoute: ApiMemoryRoute,
  ApiNotesRoute: ApiNotesRoute,
  ApiRemembersRoute: ApiRemembersRoute,
  ApiShitpostsRoute: ApiShitpostsRoute,
  ApiSongsRoute: ApiSongsRoute,
  ApiTasksRoute: ApiTasksRoute,
  ApiUnlockRoute: ApiUnlockRoute,
  ApiPublicMoRoute: ApiPublicMoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
